version: '3.8'

services:
  nodejs:
    build:
      context: ./server  # Path to the Node.js server folder
      dockerfile: Dockerfile
    container_name: nodejs-app
    working_dir: /app
    volumes:
      - ./server:/app  # Mount local server folder for live reloading
      - /app/node_modules  # Prevents mounting node_modules for isolated dependencies
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres  # Waits for PostgreSQL to be ready

  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data even if the container restarts
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Change to your desired email
      PGADMIN_DEFAULT_PASSWORD: admin  # Change to your desired password
    ports:
      - "5050:80"  # Access pgAdmin at http://localhost:5050
    depends_on:
      - postgres  # Waits until postgres service is ready

volumes:
  postgres-data:
