name: FastAPI CI Pipeline

on:
  pull_request:
    branches:
      - develop

env:
  POSTGRES_USER: test_user
  POSTGRES_PASSWORD: test_password
  POSTGRES_DB: test_db
  PGADMIN_DEFAULT_EMAIL: admin@admin.com
  PGADMIN_DEFAULT_PASSWORD: admin

jobs:
  lint-and-build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run linting
        working-directory: ./server
        run: |
          flake8 . --max-line-length=100 --exclude=__pycache__,.venv

      - name: Build and test Docker containers
        run: |
          docker-compose build
          docker-compose up -d
          # Wait for FastAPI to be ready (adjust timeout as needed)
          timeout 30 bash -c 'until curl -f http://localhost:3000/docs; do sleep 1; done'
          docker-compose logs fastapi
          docker-compose down -v
