name: CI

on:
  pull_request:
    branches:
      - develop

env:
  POSTGRES_USER: test_user
  POSTGRES_PASSWORD: test_password
  POSTGRES_DB: test_db
  PGADMIN_DEFAULT_EMAIL: admin@admin.com
  PGADMIN_DEFAULT_PASSWORD: admin
  COMPOSE_PROJECT_NAME: ba-backend

jobs:
  test-and-lint:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib postgresql-server-dev-all python3-dev

      - name: Install Python dependencies
        working-directory: ./server
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary
          pip install -r requirements.txt
          pip install flake8

      - name: Run linting
        working-directory: ./server
        run: |
          flake8 . --max-line-length=100 --exclude=__pycache__,.venv

      - name: Run tests
        working-directory: ./server
        run: |
          pytest -v --cov=. --cov-report=term-missing

      - name: Cleanup
        if: always()
        run: |
          docker compose down -v --remove-orphans