name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  test-and-lint:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build FastAPI image
        run: docker compose build fastapi

      - name: Run linting and tests
        run: |
          docker compose run --rm fastapi bash -c '
            pip install -r requirements.txt
            pip install flake8 pytest pytest-cov
            echo "Running flake8..."
            flake8 . --max-line-length=100 --exclude=__pycache__,.venv
            echo "Running tests..."
            pytest -v --cov=. --cov-report=term-missing
          '

      - name: Cleanup
        if: always()
        run: docker compose down --remove-orphans
