name: CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  test-and-lint:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install -r server/requirements.txt

      - name: Run linting
        run: |
          cd server
          flake8 . --max-line-length=100 --exclude=__pycache__,.venv,migrations

      - name: Run tests
        run: |
          cd server
          pytest -v --cov=. --cov-report=term-missing
